<a href="https://colab.research.google.com/github/gopiBNK/gopiBNK/blob/main/app.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import streamlit as st
from class_database import DatabaseManager
from class_crud import CRUDoperations

# Initialize Database Manager and CRUD operations
db_manager = DatabaseManager(db_name="zomato.db")
crud = CRUDoperations(db_manager)

# Title of the app
st.title("Zomato - Food Delivery Data Insights")

# Sidebar navigation with CRUD operations and Queries
option = st.sidebar.selectbox(
    "Choose an option",
    ["CRUD Operations", "Execute Queries"]
)

# CRUD Operations options
if option == "CRUD Operations":
    crud_option = st.sidebar.selectbox(
        "Choose CRUD Operation",
        ["Create Table", "Delete Table", "Alter Table", "Update Table", "View Tables", "Insert Data"]
    )

    # Handle CRUD operations
    if crud_option == "Create Table":
        st.subheader("Create Table")
        crud.create_table()

    elif crud_option == "Delete Table":
        st.subheader("Delete Table")
        crud.delete_table()

    elif crud_option == "Alter Table":
        st.subheader("Alter Table")
        crud.alter_table()

    elif crud_option == "Update Table":
        st.subheader("Update Table")
        crud.update_table()

    elif crud_option == "View Tables":
        st.subheader("View Tables")
        crud.view_tables()

    elif crud_option == "Insert Data":
        st.subheader("Insert Data")
        crud.insert_data()

# Queries option
elif option == "Execute Queries":
    query_option = st.sidebar.selectbox(
        "Choose a Query",
        [
            "SELECT * FROM Customers",
            "SELECT * FROM Customers WHERE customer_id = 1",
            "SELECT * FROM Restaurants",
            "SELECT * FROM Restaurants WHERE is_active = 1",
            "SELECT * FROM Orders WHERE customer_id = 1",
            "SELECT * FROM Orders WHERE restaurant_id = 5",
            "SELECT * FROM Deliveries WHERE order_id = 3",
            "SELECT rating FROM Restaurants WHERE restaurant_id = 1",
            "SELECT * FROM Orders WHERE feedback_rating = 5;",
            "SELECT total_orders FROM Customers WHERE customer_id = 1",
            "SELECT * FROM Deliveries WHERE delivery_person_id = 2",
            "SELECT * FROM Orders WHERE status = 'Delivered'",
            "SELECT SUM(total_amount) FROM Orders WHERE restaurant_id = 5",
            "SELECT * FROM Customers WHERE is_premium = 1",
            "SELECT average_delivery_time FROM Restaurants WHERE restaurant_id = 1",
            "SELECT total_deliveries FROM DeliveryPersons WHERE delivery_person_id = 3",
            "SELECT * FROM Customers WHERE preferred_cuisine = 'Italian'",
            "SELECT delivery_fee FROM Deliveries WHERE order_id = 4",
            "SELECT * FROM Orders WHERE discount_applied > 0",
            "SELECT cuisine_type, SUM(total_orders) FROM Restaurants GROUP BY cuisine_type",
        ]
    )

    st.subheader("Execute Query")
    st.write(f"Executing query: `{query_option}`")

    # Execute the query when button is pressed
    if st.button("Execute Query"):
        try:
            data = db_manager.fetch_data(query_option)
            if data is not None and not data.empty:
                st.write(data)
            else:
                st.warning("Query executed successfully, but no data found.")
        except Exception as e:
            st.error(f"Error executing query: {e}")